CHANGELOG.md, src/NamingStrategy/ArrayMapNamingStrategy.php, src/NamingStrategy/CompositeNamingStrategy.php, src/NamingStrategy/IdentityNamingStrategy.php, src/Strategy/BooleanStrategy.php, src/Strategy/DateTimeFormatterStrategy.php, src/Strategy/ExplodeStrategy.php, src/Strategy/StrategyChain.php
This patch completes #2, marking classes `final` as they were originally in zend-stdlib.
=> Re-instate `final` visibility

.travis.yml, composer.json, src/Aggregate/AggregateHydrator.php, src/DelegatingHydratorFactory.php, src/HydratorPluginManager.php, test/Aggregate/AggregateHydratorTest.php, test/DelegatingHydratorFactoryTest.php, test/HydratorManagerTest.php
Re #15: against develop this time!
According to https://github.com/zendframework/maintainers/wiki/ZF3-ServiceManager-component-refactors,-phase-2 I'd be throwing an InvalidServiceException from validate() but that breaks tests. Is this the intention for v2?
=> Changes for zend-servicemanager v3

.travis.yml, composer.json, src/Aggregate/AggregateHydrator.php, src/DelegatingHydrator.php, src/DelegatingHydratorFactory.php, src/HydratorPluginManager.php, test/Aggregate/AggregateHydratorTest.php, test/DelegatingHydratorFactoryTest.php, test/DelegatingHydratorTest.php, test/HydratorManagerTest.php, test/HydratorPluginManagerCompatibilityTest.php
This patch builds on #17, incorporating feedback and adding more dependency constraints and test builds.
In particular:
- zend-hydrator v2 and zend-stdlib v2 are incompatible. Additionally, zend-stdlib v3 and zend-eventmanager v2 are incompatible. As such, this version **MUST** target zend-stdlib and zend-eventmanager v3; that change has been made. An additional pull request against the 1.X series will be made shortly, providing forwards-compatibility for those releases.
- adds a build job per SM version, per PHP version.
- Updates the `DelegatingHydratorFactory` to ensure that the `DelegatingHydrator` it creates *always* receives a `HydratorPluginManager` instance.
- Fixes broken `AggregateHydrator` tests due to targetting v3 of zend-eventmanager; the `EventManagerInterface` in v2 did …
=> Finalize forwards-compatibility support for zend-hydrator v2

src/HydratorPluginManagerFactory.php, test/HydratorPluginManagerFactoryTest.php
Per https://discourse.zendframework.com/t/validatormanager-not-calling-custom-validator-factory/109/5?u=matthew the `hydrators` config key is not honored currently unless the application is within a zend-mvc context. This is due to the fact that `Zend\Hydrator\Module` wires configuration for the `Zend\ModuleManager\Listener\ServiceListener` in order to push merged service configuration into the plugin during bootstrap; no similar logic is available when not in a zend-mvc context, however.
This patch fixes that situation by modifying the `HydratorPluginManagerFactory` to do the following:
- If a `ServiceListener` service exists, it returns the plugin manager immediately (old behavior).
- Otherwise, it checks for the `config` service, and, if found, a `hydrators` key with an array value. …
=> Ensure `hydrators` config is honored in non-zend-mvc contexts

src/AbstractHydrator.php
It allows IDEs to not warn when addStrategy methods are chained
that hydrator interface don't hav addStrategy method.
=> [DOC] Fix a minor phpdoc comment

test/Aggregate/HydratorListenerTest.php, test/Filter/OptionalParametersFilterTest.php, test/HydratorClosureStrategyTest.php, test/HydratorStrategyTest.php, test/HydratorTest.php, test/Iterator/HydratingArrayIteratorTest.php, test/Iterator/HydratingIteratorIteratorTest.php, test/NamingStrategy/CompositeNamingStrategyTest.php, test/NamingStrategy/MapNamingStrategyTest.php, test/ObjectPropertyTest.php, test/Strategy/BooleanStrategyTest.php, test/Strategy/DateTimeFormatterStrategyTest.php, test/Strategy/ExplodeStrategyTest.php, test/Strategy/SerializableStrategyTest.php
This PR
💁 For reference, see [`composer.json`](https://github.com/zendframework/zend-hydrator/blob/master/composer.json#L16).
=> Fix: Use class keyword

test/Aggregate/AggregateHydratorFunctionalTest.php, test/Aggregate/AggregateHydratorTest.php, test/Aggregate/HydratorListenerTest.php, test/ArraySerializableTest.php, test/ClassMethodsTest.php, test/DelegatingHydratorTest.php, test/Filter/OptionalParametersFilterTest.php, test/HydratorClosureStrategyTest.php, test/HydratorObjectPropertyTest.php, test/HydratorStrategyTest.php, test/HydratorTest.php, test/ReflectionTest.php
This PR
💁 This is the visibility as declared on the parent, there's no need to increase it.
=> Fix: Reduce visibility of setUp()

test/HydratorObjectPropertyTest.php
=> Fix: Typo in namespace

src/Filter/NumberOfParameterFilter.php, src/NamingStrategy/MapNamingStrategy.php, test/Iterator/HydratingArrayIteratorTest.php, test/Iterator/HydratingIteratorIteratorTest.php, test/Strategy/SerializableStrategyTest.php
=> Fix: Typos in method names and docblocks

test/HydratorObjectPropertyTest.php
=> Fix: Declare field otherwise declared dynamically

.travis.yml, composer.lock
This PR
💁 Running
```
$ composer validate
```
on current `master` yields
```
./composer.json is valid
The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update`.
```
=> Fix: Update composer.lock

composer.json, composer.lock
❗️ Blocks #53.
This PR
💁‍♂️ This fixes an issue where tests are failing with
```
PHP Fatal error:  Call to undefined method ZendTest\Hydrator\HydratorPluginManagerCompatibilityTest::expectException() in /Users/am/Sites/zendframework/zend-hydrator/vendor/zendframework/zend-servicemanager/src/Test/CommonPluginManagerTrait.php on line 56
PHP Stack trace:
PHP   1. {main}() /Users/am/Sites/zendframework/zend-hydrator/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /Users/am/Sites/zendframework/zend-hydrator/vendor/phpunit/phpunit/phpunit:52
PHP   3. PHPUnit_TextUI_Command->run() /Users/am/Sites/zendframework/zend-hydrator/vendor/phpunit/phpunit/src/TextUI/Command.php:100
PHP   4. PHPUnit_TextUI_TestRunner->doRun() …
```
=> Fix: Allow to install phpunit/phpunit:^5.2

doc/book/strategy.md, src/Filter/NumberOfParameterFilter.php
patch contains some spelling fixes ( just in comments ) as found by a bot ( http://www.misfix.org, https://github.com/ka7/misspell_fixer ). Any upcoming License changes (e.g. GPL2 to GPL3+) are hereby granted.
=> spelling fixes

src/AbstractHydrator.php, test/ArraySerializableTest.php, test/ClassMethodsTest.php, test/HydratorTestTrait.php, test/ObjectPropertyTest.php, test/ReflectionTest.php, test/TestAsset/SimpleEntity.php
All hydrators hydrate values by calling `$this->hydrateValue($this->hydrateName($originalName, $data), $value, $data)` _(simplified)_.
Only ClassMethods calls `hydrateValue` with the original array key passed to `hydrate`: `$this->hydrateValue($originalName, $value, $data)` _(simplified)_
=> Bugfix: ClassMethods strategies tied to original name 

src/ClassMethods.php, test/HydratorTest.php
Enable/disable the use of magic __call method during hydration by setting a flag to true/false (allows __call by default because of BC)
See also: doctrine/DoctrineModule#560
=> ClassMethods: Add switch to prevent the call of __call as setter

src/Strategy/CollectionStrategy.php, test/Strategy/CollectionStrategyTest.php, test/TestAsset/User.php
This PR
💁‍♂️ The idea is to turn what would otherwise need implementation in user land code into a generic strategy, which can then be used like this, for example:
```php
<?php
namespace Localheinz\Hydrator;
use Zend\Hydrator\HydratorInterface;
use Zend\Hydrator\Reflection;
use Zend\Hydrator\Strategy;
final class UserGroupHydrator implements HydratorInterface
{
/**
* @var Reflection
*/
private $hydrator;
public function __construct(Strategy\StrategyInterface $resultsStrategy = null, Reflection $hydrator = null)
{
$this->hydrator = $hydrator ?: new Reflection();
$this->hydrator->addStrategy('users', new Strategy\CollectionStrategy(
new Reflection(),
User::class
));
}
public function extract($object)
{
throw new \BadMethodCallException('Extraction is not supported');
}
/**
* @param array …
```
=> Enhancement: Implement CollectionStrategy

.travis.yml, composer.json, composer.lock
- added php 7.2 and php nightly in travis
- removed hhvm in travis
=> added php 7.2 and php nightly in travis

src/ArraySerializable.php, test/ArraySerializableTest.php
The fix introduced in #65 did a recursive merge of the data provided when hydrating an `ArraySerializable` object. However, array _values_ should not be merged, as changes to them are generally not patches, but rather replacements, as noted in #66.
This patch provides tests demonstrating the issues noted in #66, and modifies the `ArraySerializable` hydration logic to use `array_merge()` instead of `Zend\Stdlib\ArrayUtils::merge()`; all previous tests pass now, as do the newly added tests.
Fixes #66.
=> Ensures that array values within an `ArraySerializable` are replaced

docs/book/quick-start.md
Also:
- Add comment explaining the hydrate line, to be consistent with the extract
line.
- Clarify language in extract line.
=> Fix example in quick start - hydrate returns an object.

src/Strategy/DateTimeFormatterStrategy.php, test/Strategy/DateTimeFormatterStrategyTest.php
Hey guys,
I would like to use special chars for the date format, e.g. to ensure that if I pass a MySQL `date` string to the hydrator, an object with time reset to 0 is being returned.
Therefore, I had to strip un-escaped special chars (*, !, | and +) ([documentation](http://php.net/manual/en/datetime.createfromformat.php#refsect1-datetime.createfromformat-parameters)) from the format being passed to the `DateTimeInterface::format` method.
=> DateTimeFormatterStrategy passes special characters used by `date_create_from_format` to `date_format`

docs/book/strategy.md, src/Strategy/DateTimeFormatterStrategy.php, test/Strategy/DateTimeFormatterStrategyTest.php
which converts `$value` to `DateTime` when `DateTime::createFromFormat` fails.
This is useful when hydrating dates which are in *various standardized formats* and can be handled by `new DateTime($dateString)`.
```php
$strategy = new Zend\Hydrator\Strategy\DateTimeFormatterStrategy('Y-m-d H:i:s.uP', null, true);
$hydrated1 = $strategy->hydrate( '2016-03-04 10:29:40+01'); // before PR this won't pass
$hydrated2 = $strategy->hydrate( '2016-03-04 10:29:40.123456+01');
```
=> Added optional $dateTimeFallback to DateTimeFormatterStrategy

CHANGELOG.md, docs/book/v3/migration.md, src/NamingStrategy/MapNamingStrategy.php, test/NamingStrategy/MapNamingStrategyTest.php
Per #85, we should not allow direct instantiation of a `MapNamingStrategy`, as users porting from v2 to v3 code should learn immediately that they need to switch to one of the named constructors.
Fixes #85.
=> Do not allow direct instantiation of a MapNamingStrategy

CHANGELOG.md, docs/book/v3/filter.md, docs/book/v3/migration.md, docs/book/v3/naming-strategy/intro.md, docs/book/v3/strategy.md, mkdocs.yml, src/AbstractHydrator.php, src/ClassMethods.php, src/Filter/FilterEnabledInterface.php, src/NamingStrategy/NamingStrategyEnabledInterface.php, src/Reflection.php, src/Strategy/StrategyEnabledInterface.php
This patch does the following:
- It moves each `*EnabledInterface` to the proper subnamespace (for some reason, these were created in the top-level namespace, and should not be).
- It updates `AbstractHydrator` such that it no longer needs a constructor:
- `$strategies` is now defined initially as an empty array.
- `$filterComposite` gets lazy-loaded by a new method, `getCompositeFilter()`; all references to `$filterComposite` were updated to use this new method in order to guarantee a `FilterComposite` instance is used.
Functionality remains the same, and all tests continue to pass.
I have also updated documentation and added migration notes.
=> Move *EnabledInterface definitions to appropriate namespaces

CHANGELOG.md, docs/book/v3/migration.md, docs/book/v3/plugin-managers.md, mkdocs.yml, src/ConfigProvider.php, src/DelegatingHydratorFactory.php, src/Exception/MissingHydratorServiceException.php, src/HydratorPluginManager.php, src/HydratorPluginManagerFactory.php, src/HydratorPluginManagerInterface.php, src/StandaloneHydratorPluginManager.php, src/StandaloneHydratorPluginManagerFactory.php, test/StandaloneHydratorPluginManagerFactoryTest.php, test/StandaloneHydratorPluginManagerTest.php
This patch allows zend-hydrator to be used without zend-servicemanager, making that package a truly optional dependency.
First, it adds `Zend\Hydrator\HydratorPluginManagerInterface`, which extends the PSR-11 `ContainerInterface`. This is done to ensure that any plugin manager implementation complies with PSR-11 (currently, `AbstractPluginManager` implementations from zend-servicemanager do not), as well as to allow type-hinting on that interface when a plugin manager is needed. The `DelegatingHydratorFactory` was updated to test against this interface instead of the `HydratorPluginManager`.
Next, the patch adds `Zend\Hydrator\StandaloneHydratorPluginManager`, which provides a minimal plugin manager that supports loading *only the shipped hydrator implementations*. A factory for creating …
=> Provide a standalone plugin manager implementation

docs/book/v3/strategy.md
Added `Zend\Hydrator\Strategy\DateTimeFormatterStrategy` docs was lost during PR #80
=> Added Zend\Hydrator\Strategy\DateTimeFormatterStrategy docs

CHANGELOG.md, composer.json, composer.lock, phpcs.xml, src/ArraySerializable.php, src/ClassMethods.php, src/ObjectProperty.php, src/Reflection.php, test/ArraySerializableTest.php, test/ClassMethodsTest.php, test/ObjectPropertyTest.php, test/ReflectionTest.php
It should help with migrations. Not sure why it was not added here, maybe there is some reasoning not to adding it?
=> Trigger user deprecated error on deprecated classes

CHANGELOG.md, docs/book/v3/migration.md, docs/book/v3/naming-strategy/map-naming-strategy.md, src/NamingStrategy/MapNamingStrategy.php, test/NamingStrategy/MapNamingStrategyTest.php
Provide a narrative description of what you are trying to accomplish:
`Zend\Hydrator\NamingStrategy\MapNamingStrategy::createFromAssymetricMap` is not static, as [documentation](https://docs.zendframework.com/zend-hydrator/v3/naming-strategy/map-naming-strategy/#both-hydration-and-extraction-maps) mentions. Moreover, its constructor is private, so the method cannot be accessed from an instance.
This PR adds the `static` keyword to the `createFromAssymetricMap` method, and duplicates it to fix a misspelling, while avoiding BC break.
=> Fixed static on MapMapping asymmetric method and its misspell

src/NamingStrategy/UnderscoreNamingStrategy/CamelCaseToUnderscoreFilter.php, test/NamingStrategy/UnderscoreNamingStrategy/CamelCaseToUnderscoreFilterTest.php, test/NamingStrategy/UnderscoreNamingStrategy/UnderscoreToCamelCaseFilterTest.php
Patch #14 inlined the `CamelCaseToUnderscore` and `UnderscoreToCamelCase` filters in the package. However, in doing so, it added behavior that was not expected, nor present in the original: splitting words on numeric boundaries.
Furthermore, the functionality was unpredictable; some boundaries were matched, while others were not, which led to an inability to predict what would happen.
The problem stemmed from the addition of a regex in each of the unicode and non-unicode matching pattern sets, as well as corresponding replacement sets. These have been reverted to match those in zend-filter, which restores behavior to how it worked in version 2.
Additional test cases were provided to the `UnderscoreToCamelCaseTest` to demonstrate the reverse operations as well. One note: when converting …
=> Restore original behavior of UnderscoreNamingStrategy
